### ISSUE TITLE
Typo on cover

### ISSUE THREAD

**Issue by dave-theunsub** [DinisCruz/Book_Generation_Z_Developer#8]
The cover has 

> Key concepts and ideas to help you get a better job as an developer

The "an" should be "a" (i.e., `better job as a developer`).

Minor nitpick, but very noticeable on the cover.

**Comment by 1lastBr3ath** [comment]
There are many typos and grammar mistakes. This, indeed, needs a thorough proofreading. We can rather improve it as we go. I guess, it's still in beta and a lot is still to come.

**Comment by DinisCruz** [comment]
Thanks @dave-theunsub 

Just fixed it on Canva

![image](https://user-images.githubusercontent.com/656739/37064029-605784d4-2193-11e8-8060-b7846548ffe3.png)

@1lastBr3ath yap the idea is to improve it as we go along :)

and yes @dave-theunsub the text still needs a big review for typos and bad english. At the moment I'm focusing on adding content

**Comment by DinisCruz** [comment]
Fix live on site

![image](https://user-images.githubusercontent.com/656739/37064174-d6faf684-2193-11e8-9e17-1ae5d81cb350.png)
